export const structSubData = [
  {
    title: "Uglevodorod ishlab chiqarish",
    imgName: "img1.png",
    data: [
      "Muborak neft va gaz qazib olish bo'limi",
      "Sho’rtan neft va gaz qazib olish bo'limi",
      "Ustyurt neft va gaz qazib olish bo'limi",
      "Gazli neft va gaz qazib olish bo'limi",
      "Andijon neft va gaz qazib olish bo'limi",
    ],
  },
  {
    title: "Neft va gazni qayta ishlash",
    imgName: "img2.png",
    data: [
      "Muborak gazni qayta ishlash zavodi",
      "“Sho’rtan gaz kimyoviy kompleksi” MChJ",
      "“Buxoro neftni qayta ishlash zavodi” MChJ",
      "“Chinoz neftni qayta ishlash zavodi” MChJ",
      "“Uzbekistan GTL” MChJ",
      "Mahsusenergogaz AJ",
    ],
  },
  {
    title: "Neft mahsulotlarini tashish va saqlash",
    imgName: "img3.png",
    data: [
      "“Taxiatosh neft baza” MChJ",
      "“Andijon neft baza” MChJ",
      "“Buxoro neft baza” MChJ",
      "“Jizzax neft baza” MChJ",
      "“Qarshi neft baza” MChJ",
      "“Navoiy neft baza” MChJ",
      "“To’raqo’rg’on neft baza” MChJ",
      "“Maroqand neft baza” MChJ",
      "“Termiz neft baza” MChJ",
      "“Guliston neft baza” MChJ **",
      "“Paxta neft baza” MChJ",
      "“Chinobod neft baza” MChJ",
      "“Kuchluk neft baza” MChJ",
      "“Farg’ona neft baza” MChJ **",
      "“Urgench neft baza” MChJ",
    ],
  },
  {
    title: "Neft mahsulotlarini sotish",
    imgName: "img4.png",
    data: ["“UNG Petro” MChJ"],
  },
  {
    title: "Tadqiqot va loyihalash ishlari",
    imgName: "img5.png",
    data: ["“O’ZLITINEFTGAZ” AJ", "“Neft va gaz jurnali” MChJ"],
  },
  {
    title: "Kadrlarni tayyorlash",
    imgName: "img6.png",
    data: [
      "I. M. Gubkina nomidagi Rossiya davlat neft va gaz universiteti Toshkent filiali",
      "Buxoro neft va gaz sanoati kasb-hunar kolleji",
      "Farg’ona neft va gaz sanoati kasb-hunar kolleji",
      "“UNG training” MChJ",
    ],
  },
  {
    title: "Servis",
    imgName: "img7.png",
    data: [
      "Ochiq neft va gaz favvoralarining oldini olish va yo'q qilish bo'yicha O'zbekiston harbiylashtirilgan bo'limi",
      "“Uzneftgazquduq ta’mirlash” AJ",
      "“Neft gaz bino inshoat” MChJi",
      "“Uzneftgazburg’ulash ishlari” MChJ",
      "“Muboraksuvta’minot” Unitar korxonasi",
    ],
  },
];
